# Generated by Django 4.2.7 on 2024-07-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('immatriculation', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
            ],
        ),
    ]
